# HTTP
quarkus.http.port=8085

# Frontend URL (used in email links ? frontend calls POST /api/users/activate with token in body)
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
quarkus.log.category."io.quarkus.mailer".level=DEBUG

# Mailer (MailHog para desarrollo)
quarkus.mailer.host=${MAIL_HOST:localhost}
quarkus.mailer.port=${MAIL_PORT:1025}
quarkus.mailer.start-tls=DISABLED
quarkus.mailer.auth-methods=DISABLED
quarkus.mailer.from=${MAIL_FROM:noreply@kitti.es}
quarkus.mailer.mock=false

# Container image
quarkus.container-image.builder=jib
quarkus.container-image.group=ciscoadiz
quarkus.container-image.name=notification-service
quarkus.container-image.tag=latest

# Kafka
kafka.bootstrap.servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
mp.messaging.incoming.user-registered.connector=smallrye-kafka
mp.messaging.incoming.user-registered.topic=user-registered
mp.messaging.incoming.user-registered.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.user-registered.group.id=notification-service
mp.messaging.incoming.adoption-form-analysed.connector=smallrye-kafka
mp.messaging.incoming.adoption-form-analysed.topic=adoption-form-analysed
mp.messaging.incoming.adoption-form-analysed.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.adoption-form-analysed.group.id=notification-service

%test.mp.messaging.incoming.adoption-form-analysed.connector=smallrye-in-memory

# Test
%test.quarkus.mailer.mock=true
%test.mp.messaging.incoming.user-registered.connector=smallrye-in-memory
%test.quarkus.http.test-port=0

# Prod
%prod.quarkus.swagger-ui.enabled=false
%prod.quarkus.smallrye-openapi.enabled=false

quarkus.otel.exporter.otlp.endpoint=${OTEL_ENDPOINT:http://localhost:4317}
quarkus.otel.service.name=notification-service
quarkus.otel.logs.enabled=true
quarkus.otel.metrics.enabled=true
%test.quarkus.otel.sdk.disabled=true
%dev.quarkus.otel.sdk.disabled=true
