# HTTP
quarkus.http.port=8085
quarkus.log.category."io.quarkus.mailer".level=DEBUG

# Mailer (MailHog para desarrollo)
quarkus.mailer.host=${MAIL_HOST:localhost}
quarkus.mailer.port=${MAIL_PORT:1025}
quarkus.mailer.start-tls=DISABLED
quarkus.mailer.auth-methods=DISABLED
quarkus.mailer.from=${MAIL_FROM:kittigram@ciscoadiz.org}
quarkus.mailer.mock=false

# Container image
quarkus.container-image.builder=jib
quarkus.container-image.group=ciscoadiz
quarkus.container-image.name=notification-service
quarkus.container-image.tag=latest

# Kafka
kafka.bootstrap.servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
mp.messaging.incoming.user-registered.connector=smallrye-kafka
mp.messaging.incoming.user-registered.topic=user-registered
mp.messaging.incoming.user-registered.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.user-registered.group.id=notification-service

# Test
%test.quarkus.mailer.mock=true
%test.mp.messaging.incoming.user-registered.connector=smallrye-in-memory