services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  minio:
    image: minio/minio:latest
    command: server /data --address ":9000" --console-address ":9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    container_name: kafka-ui
    depends_on:
      - kafka
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8008:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./docker/alloy/config.alloy:/etc/alloy/config.alloy:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    ports:
      - "4317:4317"
      - "4318:4318"
      - "12345:12345"
    environment:
      GRAFANA_LOKI_URL: ${GRAFANA_LOKI_URL}
      GRAFANA_LOKI_USER: ${GRAFANA_LOKI_USER}
      GRAFANA_PROMETHEUS_URL: ${GRAFANA_PROMETHEUS_URL}
      GRAFANA_PROMETHEUS_USER: ${GRAFANA_PROMETHEUS_USER}
      GRAFANA_TEMPO_URL: ${GRAFANA_TEMPO_URL}
      GRAFANA_TEMPO_USER: ${GRAFANA_TEMPO_USER}
      GRAFANA_API_KEY: ${GRAFANA_API_KEY}

volumes:
  postgres_data:
  minio_data: