-- No seed data needed: authorization checks (requireAdmin, requireMember) query
-- membership tables which return false/0 for any non-existent org, producing the
-- correct 403 without the org needing to exist in the DB.
