-- Crear schema si no existe
CREATE SCHEMA IF NOT EXISTS cats;

-- Crear secuencias
CREATE SEQUENCE IF NOT EXISTS cats.cats_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS cats.cat_images_SEQ START WITH 1 INCREMENT BY 50;
