# HTTP
quarkus.http.port=8080

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,Accept
quarkus.http.cors.exposed-headers=Location,Content-Type,Authorization
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.access-control-max-age=86400

# JWT verificación
mp.jwt.verify.issuer=https://kittigram.ciscoadiz.org
mp.jwt.verify.publickey.location=publicKey.pem

# URLs de servicios internos
quarkus.rest-client.user-service.url=${USER_SERVICE_URL:http://localhost:8081}
quarkus.rest-client.auth-service.url=${AUTH_SERVICE_URL:http://localhost:8082}
quarkus.rest-client.cat-service.url=${CAT_SERVICE_URL:http://localhost:8084}
quarkus.rest-client.storage-service.url=${STORAGE_SERVICE_URL:http://localhost:8083}

# Container image
quarkus.container-image.builder=jib
quarkus.container-image.group=ciscoadiz
quarkus.container-image.name=gateway-service
quarkus.container-image.tag=latest