# Base de datos
quarkus.datasource.db-kind=postgresql

%dev.quarkus.datasource.username=${DB_USER:kittigram}
%dev.quarkus.datasource.password=${DB_PASSWORD:kittigram}
%dev.quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kittigram}

%prod.quarkus.datasource.username=${DB_USER:kittigram}
%prod.quarkus.datasource.password=${DB_PASSWORD:kittigram}
%prod.quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kittigram}

%test.quarkus.datasource.devservices.image-name=postgres:16

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.log.sql=false

# gRPC servidor
quarkus.grpc.server.port=9090
%test.quarkus.grpc.server.port=0

# JWT
mp.jwt.verify.issuer=https://kittigram.ciscoadiz.org
mp.jwt.verify.publickey.location=publicKey.pem

# HTTP
quarkus.http.port=8081

# Mailer
%test.quarkus.mailer.mock=true

# Container image
quarkus.container-image.build=true
quarkus.container-image.push=false
quarkus.container-image.builder=jib
quarkus.container-image.group=ciscoadiz
quarkus.container-image.name=user-service
quarkus.container-image.tag=latest

# Kafka
kafka.bootstrap.servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
mp.messaging.outgoing.user-registered.connector=smallrye-kafka
mp.messaging.outgoing.user-registered.topic=user-registered
mp.messaging.outgoing.user-registered.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
%test.mp.messaging.outgoing.user-registered.connector=smallrye-in-memory

%test.quarkus.datasource.devservices.init-script-path=init-test.sql