# Base de datos
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:kittigram}
quarkus.datasource.password=${DB_PASSWORD:kittigram}
quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kittigram}

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true

# gRPC servidor
quarkus.grpc.server.port=9090

# JWT
mp.jwt.verify.issuer=https://kittigram.ciscoadiz.org
mp.jwt.verify.publickey.location=publicKey.pem

# HTTP
quarkus.http.port=8081

# Container image
quarkus.container-image.build=true
quarkus.container-image.push=false
quarkus.container-image.builder=jib
quarkus.container-image.group=ciscoadiz
quarkus.container-image.name=user-service
quarkus.container-image.tag=latest