# HTTP
quarkus.http.port=8088

# Base de datos
quarkus.datasource.db-kind=postgresql

%dev.quarkus.datasource.username=${DB_USER:kitties}
%dev.quarkus.datasource.password=${DB_PASSWORD:kitties}
%dev.quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kitties}?search_path=organization

%prod.quarkus.datasource.username=${DB_USER:kitties}
%prod.quarkus.datasource.password=${DB_PASSWORD:kitties}
%prod.quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kitties}?search_path=organization
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kitties}

# Flyway
quarkus.flyway.enabled=false
%prod.quarkus.flyway.enabled=true
%prod.quarkus.flyway.migrate-at-start=true
%prod.quarkus.flyway.schemas=organization
%prod.quarkus.flyway.locations=classpath:db/migration

%prod.quarkus.hibernate-orm.schema-management.strategy=validate

%test.quarkus.datasource.devservices.image-name=postgres:16
%test.quarkus.datasource.devservices.init-script-path=init-test.sql
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=import-test.sql
%test.quarkus.hibernate-orm.log.sql=false

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true

# JWT
mp.jwt.verify.issuer=https://www.kitti.es
mp.jwt.verify.publickey.location=publicKey.pem
%prod.mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:/run/secrets/publicKey.pem}

# Container image
quarkus.container-image.builder=jib
quarkus.container-image.group=ciscoadiz
quarkus.container-image.name=organization-service
quarkus.container-image.tag=latest
