# HTTP
quarkus.http.port=8083
storage.public.url=http://localhost:8080/api

# S3 / MinIO
quarkus.s3.endpoint-override=http://localhost:9000
quarkus.s3.path-style-access=true
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.type=static
quarkus.s3.async-client.type=netty
quarkus.s3.aws.credentials.static-provider.access-key-id=${MINIO_ROOT_USER:kitties}
quarkus.s3.aws.credentials.static-provider.secret-access-key=${MINIO_ROOT_PASSWORD:change_me_min16chars}

# Bucket
bucket.name=${MINIO_DEFAULT_BUCKETS:kitties}

# Container image
quarkus.container-image.builder=jib
quarkus.container-image.group=ciscoadiz
quarkus.container-image.name=storage-service
quarkus.container-image.tag=latest

# OpenAPI / Swagger UI
quarkus.smallrye-openapi.info-title=Storage Service API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=File storage and retrieval service for Kitties (S3/MinIO backend)
quarkus.swagger-ui.always-include=false

%prod.quarkus.swagger-ui.enabled=false
%prod.quarkus.smallrye-openapi.enabled=false
